import dotenv from "dotenv";
import Product from "../models/Product.js";
import { connectDatabase } from "../config/db.js";
import productImages from "./productImages.json" with { type: "json" };

dotenv.config();

// ===========================================================================
// IMMAGINI --------------------------------------------------------------------
// Le URL Cloudinary reali vivono in productImages.json (generato da
// `node scripts/syncCloudinaryImages.js`). Se un prodotto non ha ancora
// un'immagine caricata, ricade su un placeholder con brand+model.
// ---------------------------------------------------------------------------
const ph = (label, variant = "1a1a2e") =>
  `https://placehold.co/800x800/${variant}/ffffff?text=${encodeURIComponent(label)}`;

const resolveImage = (data) => {
  const url = productImages[data.title];
  return url || ph(`${data.brand}\n${data.model}`);
};

// Helper per applicare defaults comuni. Ogni prodotto dichiara solo i campi
// che gli servono; il resto viene ereditato.
const make = (data) => {
  const image = data.image || resolveImage(data);
  return {
    markup: 15,
    stock: 10,
    isOnSale: false,
    salePrice: null,
    warrantyMonths: 24,
    highlights: [],
    image,
    images: [image],
    specifications: {},
    compatibility: {},
    ...data,
  };
};

const products = [
  // ============================================================
  // CPU (5) ----------------------------------------------------
  // ============================================================
  make({
    title: "Intel Core i9-14900K",
    shortDescription: "Flagship Intel Raptor Lake Refresh: 24 core, boost 6.0 GHz.",
    description:
      "Il top di gamma Intel di 14Âª generazione: 8 P-core + 16 E-core per 24 core totali, boost massimo a 6.0 GHz, cache L3 da 36 MB. Gestisce ogni workload tra gaming competitivo e produttivitÃ  professionale.",
    highlights: [
      "24 core / 32 thread, boost fino a 6.0 GHz",
      "Cache L3 da 36 MB",
      "Supporto DDR5-5600 e PCIe 5.0",
      "Socket LGA1700 con retro-compatibilitÃ  mobo Z690/Z790",
    ],
    componentType: "CPU",
    brand: "Intel",
    model: "Core i9-14900K",
    category: "Processors",
    priceBase: 599,
    markup: 14,
    releaseYear: 2023,
    warrantyMonths: 36,
    stock: 20,
    specifications: {
      cpu: {
        architecture: "Raptor Lake Refresh",
        coresCount: 24,
        threadsCount: 32,
        baseClockGhz: 3.2,
        boostClockGhz: 6.0,
        cacheL3Mb: 36,
        processNm: 10,
        integratedGpu: "Intel UHD Graphics 770",
      },
    },
    compatibility: { socket: "LGA1700", chipset: "Intel Z790", tdp: "125W" },
  }),
  make({
    title: "Intel Core i7-14700K",
    shortDescription: "20 core ibridi Raptor Lake Refresh a prezzo sweet-spot.",
    description:
      "Intel Core i7-14700K offre 20 core (8P + 12E) e boost fino a 5.6 GHz, 33 MB di cache L3. Ideale per chi cerca prestazioni top in gaming 1440p/4K senza salire al flagship.",
    highlights: [
      "20 core / 28 thread, boost 5.6 GHz",
      "Cache L3 33 MB",
      "Ottimo rapporto prezzo/prestazioni della serie 14",
      "Overclock aggressivo su chipset Z790",
    ],
    componentType: "CPU",
    brand: "Intel",
    model: "Core i7-14700K",
    category: "Processors",
    priceBase: 419,
    markup: 13,
    releaseYear: 2023,
    warrantyMonths: 36,
    stock: 25,
    specifications: {
      cpu: {
        architecture: "Raptor Lake Refresh",
        coresCount: 20,
        threadsCount: 28,
        baseClockGhz: 3.4,
        boostClockGhz: 5.6,
        cacheL3Mb: 33,
        processNm: 10,
        integratedGpu: "Intel UHD Graphics 770",
      },
    },
    compatibility: { socket: "LGA1700", chipset: "Intel Z790", tdp: "125W" },
  }),
  make({
    title: "Intel Core i5-14600K",
    shortDescription: "La scelta gaming 1080p/1440p: 14 core ibridi a 5.3 GHz.",
    description:
      "Processore mid-range con 14 core (6P + 8E) e boost fino a 5.3 GHz. Eccellente per build gaming fino al 1440p ad alto framerate e workload misti.",
    highlights: [
      "14 core / 20 thread, boost 5.3 GHz",
      "Cache L3 24 MB",
      "Ottimo consumo: 125W base",
      "Perfetto abbinato a GPU di fascia media",
    ],
    componentType: "CPU",
    brand: "Intel",
    model: "Core i5-14600K",
    category: "Processors",
    priceBase: 319,
    markup: 14,
    releaseYear: 2023,
    warrantyMonths: 36,
    stock: 30,
    specifications: {
      cpu: {
        architecture: "Raptor Lake Refresh",
        coresCount: 14,
        threadsCount: 20,
        baseClockGhz: 3.5,
        boostClockGhz: 5.3,
        cacheL3Mb: 24,
        processNm: 10,
        integratedGpu: "Intel UHD Graphics 770",
      },
    },
    compatibility: { socket: "LGA1700", chipset: "Intel Z790", tdp: "125W" },
  }),
  make({
    title: "AMD Ryzen 9 7950X3D",
    shortDescription: "16 core Zen 4 con 3D V-Cache: il re del gaming AM5.",
    description:
      "L'ammiraglia AMD con tecnologia 3D V-Cache: 16 core Zen 4 a 5nm e 128 MB totali di cache L3 (di cui 64 MB impilati). Prestazioni gaming al top con consumi contenuti grazie ai 120W TDP.",
    highlights: [
      "16 core / 32 thread, boost 5.7 GHz",
      "128 MB L3 totali grazie al 3D V-Cache",
      "TDP 120W, efficienza imbattibile",
      "Socket AM5 con supporto DDR5 e PCIe 5.0",
    ],
    componentType: "CPU",
    brand: "AMD",
    model: "Ryzen 9 7950X3D",
    category: "Processors",
    priceBase: 689,
    markup: 12,
    releaseYear: 2023,
    warrantyMonths: 36,
    stock: 15,
    specifications: {
      cpu: {
        architecture: "Zen 4 (3D V-Cache)",
        coresCount: 16,
        threadsCount: 32,
        baseClockGhz: 4.2,
        boostClockGhz: 5.7,
        cacheL3Mb: 128,
        processNm: 5,
        integratedGpu: "Radeon Graphics 2-core",
      },
    },
    compatibility: { socket: "AM5", chipset: "AMD X670E", tdp: "120W" },
  }),
  make({
    title: "AMD Ryzen 7 7800X3D",
    shortDescription: "Il miglior gaming CPU AM5: 8 core Zen 4 + 96 MB di V-Cache.",
    description:
      "La CPU gaming piÃ¹ efficiente sul mercato: 8 core Zen 4 con 3D V-Cache e 96 MB di L3, boost 5.0 GHz, TDP 120W. Batte anche i chip da 16 core in moltissimi giochi.",
    highlights: [
      "8 core / 16 thread, boost 5.0 GHz",
      "96 MB L3 grazie al 3D V-Cache",
      "Efficientissimo: basta un AIO 240mm",
      "Socket AM5 con roadmap fino al 2025+",
    ],
    componentType: "CPU",
    brand: "AMD",
    model: "Ryzen 7 7800X3D",
    category: "Processors",
    priceBase: 449,
    markup: 12,
    releaseYear: 2023,
    warrantyMonths: 36,
    stock: 20,
    specifications: {
      cpu: {
        architecture: "Zen 4 (3D V-Cache)",
        coresCount: 8,
        threadsCount: 16,
        baseClockGhz: 4.2,
        boostClockGhz: 5.0,
        cacheL3Mb: 96,
        processNm: 5,
      },
    },
    compatibility: { socket: "AM5", chipset: "AMD X670", tdp: "120W" },
  }),

  // ============================================================
  // GPU (5) ----------------------------------------------------
  // ============================================================
  make({
    title: "NVIDIA GeForce RTX 4090 Founders Edition",
    shortDescription: "24GB GDDR6X, DLSS 3: il mostro 4K/8K senza compromessi.",
    description:
      "Architettura Ada Lovelace con 16384 CUDA core, 24 GB di GDDR6X e supporto a DLSS 3 con Frame Generation. La scelta indiscussa per gaming 4K maxed-out e rendering 3D professionale.",
    highlights: [
      "24 GB GDDR6X a 21 Gbps",
      "16384 CUDA core + 128 RT core di 3Âª gen",
      "DLSS 3 con Frame Generation",
      "Uscite HDMI 2.1 + 3x DisplayPort 1.4a",
    ],
    componentType: "GPU",
    brand: "NVIDIA",
    model: "GeForce RTX 4090 FE",
    category: "Graphics Cards",
    priceBase: 1599,
    markup: 10,
    releaseYear: 2022,
    warrantyMonths: 36,
    weightGrams: 2200,
    color: "Nero",
    stock: 6,
    specifications: {
      gpu: {
        vramGb: 24,
        vramType: "GDDR6X",
        boostClockMhz: 2520,
        cudaCores: 16384,
        rayTracingCores: 128,
        tdpW: 450,
        lengthMm: 304,
        ports: ["HDMI 2.1", "DisplayPort 1.4a", "DisplayPort 1.4a", "DisplayPort 1.4a"],
        recommendedPsuW: 850,
      },
    },
    compatibility: { interface: "PCIe 4.0 x16", pciExpressVersion: "4.0" },
  }),
  make({
    title: "NVIDIA GeForce RTX 4080 SUPER",
    shortDescription: "16GB GDDR6X a 256-bit: 4K ultra a prezzo piÃ¹ umano.",
    description:
      "Refresh della RTX 4080 con memorie piÃ¹ veloci e 10240 CUDA core. Ottima per 4K 120 FPS nei giochi moderni con DLSS 3 attivo.",
    highlights: [
      "16 GB GDDR6X a 23 Gbps",
      "10240 CUDA core, 80 RT core",
      "DLSS 3 + Frame Generation",
      "TDP 320W, PSU 750W consigliato",
    ],
    componentType: "GPU",
    brand: "NVIDIA",
    model: "GeForce RTX 4080 SUPER",
    category: "Graphics Cards",
    priceBase: 999,
    markup: 11,
    releaseYear: 2024,
    warrantyMonths: 36,
    weightGrams: 1950,
    stock: 10,
    specifications: {
      gpu: {
        vramGb: 16,
        vramType: "GDDR6X",
        boostClockMhz: 2550,
        cudaCores: 10240,
        rayTracingCores: 80,
        tdpW: 320,
        lengthMm: 304,
        ports: ["HDMI 2.1", "DisplayPort 1.4a", "DisplayPort 1.4a", "DisplayPort 1.4a"],
        recommendedPsuW: 750,
      },
    },
    compatibility: { interface: "PCIe 4.0 x16", pciExpressVersion: "4.0" },
  }),
  make({
    title: "NVIDIA GeForce RTX 4070 Ti SUPER",
    shortDescription: "16GB per 1440p/4K: la scelta enthusiast di fascia media.",
    description:
      "Memoria aumentata a 16 GB e bus a 256-bit rispetto alla 4070 Ti originale. Eccellente per gaming 1440p ad alto framerate e 4K con DLSS.",
    highlights: [
      "16 GB GDDR6X a 256-bit",
      "8448 CUDA core, 66 RT core",
      "DLSS 3 + Frame Generation",
      "TDP 285W, PSU 700W consigliato",
    ],
    componentType: "GPU",
    brand: "NVIDIA",
    model: "GeForce RTX 4070 Ti SUPER",
    category: "Graphics Cards",
    priceBase: 799,
    markup: 12,
    releaseYear: 2024,
    warrantyMonths: 36,
    weightGrams: 1600,
    stock: 14,
    specifications: {
      gpu: {
        vramGb: 16,
        vramType: "GDDR6X",
        boostClockMhz: 2610,
        cudaCores: 8448,
        rayTracingCores: 66,
        tdpW: 285,
        lengthMm: 285,
        ports: ["HDMI 2.1", "DisplayPort 1.4a", "DisplayPort 1.4a", "DisplayPort 1.4a"],
        recommendedPsuW: 700,
      },
    },
    compatibility: { interface: "PCIe 4.0 x16", pciExpressVersion: "4.0" },
  }),
  make({
    title: "AMD Radeon RX 7900 XTX",
    shortDescription: "24GB GDDR6 RDNA 3: 4K gaming a prezzo competitivo.",
    description:
      "L'ammiraglia Radeon con architettura chiplet RDNA 3 a 5nm, 24 GB di GDDR6 e DisplayPort 2.1 nativo. Alternativa potente alla RTX 4080 con piÃ¹ VRAM.",
    highlights: [
      "24 GB GDDR6 su bus 384-bit",
      "Architettura chiplet RDNA 3",
      "DisplayPort 2.1 per monitor 8K",
      "54% piÃ¹ efficiente della gen precedente",
    ],
    componentType: "GPU",
    brand: "AMD",
    model: "Radeon RX 7900 XTX",
    category: "Graphics Cards",
    priceBase: 899,
    markup: 12,
    releaseYear: 2022,
    warrantyMonths: 24,
    weightGrams: 1700,
    stock: 12,
    specifications: {
      gpu: {
        vramGb: 24,
        vramType: "GDDR6",
        boostClockMhz: 2500,
        tdpW: 355,
        lengthMm: 287,
        ports: ["HDMI 2.1", "DisplayPort 2.1", "DisplayPort 2.1", "USB-C"],
        recommendedPsuW: 800,
      },
    },
    compatibility: { interface: "PCIe 4.0 x16", pciExpressVersion: "4.0" },
  }),
  make({
    title: "AMD Radeon RX 7800 XT",
    shortDescription: "16GB GDDR6 per 1440p ultra: rapporto prezzo/prestazioni top.",
    description:
      "Scheda sweet-spot per gaming 1440p maxed-out con FSR 3 a supporto. 16 GB di memoria VRAM rendono la 7800 XT piÃ¹ longeva delle controparti NVIDIA da 12 GB.",
    highlights: [
      "16 GB GDDR6 a 256-bit",
      "3840 stream processor RDNA 3",
      "FSR 3 con Frame Generation",
      "TDP 263W, PSU 700W consigliato",
    ],
    componentType: "GPU",
    brand: "AMD",
    model: "Radeon RX 7800 XT",
    category: "Graphics Cards",
    priceBase: 519,
    markup: 13,
    releaseYear: 2023,
    warrantyMonths: 24,
    weightGrams: 1400,
    stock: 18,
    specifications: {
      gpu: {
        vramGb: 16,
        vramType: "GDDR6",
        boostClockMhz: 2430,
        tdpW: 263,
        lengthMm: 267,
        ports: ["HDMI 2.1", "DisplayPort 2.1", "DisplayPort 2.1", "USB-C"],
        recommendedPsuW: 700,
      },
    },
    compatibility: { interface: "PCIe 4.0 x16", pciExpressVersion: "4.0" },
  }),

  // ============================================================
  // RAM (5) ----------------------------------------------------
  // ============================================================
  make({
    title: "Corsair Dominator Platinum RGB DDR5 32GB (2x16GB) 6000MHz CL30",
    shortDescription: "32GB DDR5-6000 CL30 enthusiast con RGB CAPELLIX.",
    description:
      "Kit premium DDR5 con profili XMP 3.0 / EXPO certificati, 12 LED CAPELLIX controllabili via iCUE e dissipatori in alluminio massiccio.",
    highlights: [
      "2x16GB DDR5-6000 CL30",
      "12 LED CAPELLIX controllabili iCUE",
      "Profili XMP 3.0 + AMD EXPO",
      "Garanzia limitata a vita",
    ],
    componentType: "RAM",
    brand: "Corsair",
    model: "Dominator Platinum RGB 32GB 6000",
    category: "Memory",
    priceBase: 245,
    markup: 18,
    releaseYear: 2023,
    warrantyMonths: 120,
    stock: 30,
    specifications: {
      ram: { sizeGb: 16, modulesCount: 2, speedMhz: 6000, casLatency: 30, voltage: 1.4, rgb: true },
    },
    compatibility: { memoryType: "DDR5", formFactor: "DIMM" },
  }),
  make({
    title: "G.Skill Trident Z5 RGB DDR5 32GB (2x16GB) 7200MHz CL34",
    shortDescription: "32GB DDR5-7200 CL34: tra i kit piÃ¹ veloci del mercato.",
    description:
      "Kit ultra-tirato per appassionati di tuning e benchmark. Dissipatori in alluminio con finitura dual-tone e illuminazione ARGB a doppia striscia.",
    highlights: [
      "2x16GB DDR5-7200 CL34",
      "Intel XMP 3.0 certified",
      "Dissipatore premium dual-tone",
      "Idoneo per record overclocking",
    ],
    componentType: "RAM",
    brand: "G.Skill",
    model: "Trident Z5 RGB 32GB 7200",
    category: "Memory",
    priceBase: 259,
    markup: 17,
    releaseYear: 2023,
    warrantyMonths: 120,
    stock: 22,
    specifications: {
      ram: { sizeGb: 16, modulesCount: 2, speedMhz: 7200, casLatency: 34, voltage: 1.4, rgb: true },
    },
    compatibility: { memoryType: "DDR5", formFactor: "DIMM" },
  }),
  make({
    title: "Kingston Fury Beast DDR5 32GB (2x16GB) 5600MHz CL40",
    shortDescription: "32GB DDR5-5600 con XMP 3.0 e prezzo entry-level.",
    description:
      "Kit DDR5 essenziale ma affidabile per build mainstream AM5 / LGA1700. Plug-and-play con profilo XMP preimpostato.",
    highlights: [
      "2x16GB DDR5-5600 CL40",
      "XMP 3.0 pronto all'uso",
      "Dissipatore low-profile",
      "Garanzia a vita",
    ],
    componentType: "RAM",
    brand: "Kingston",
    model: "Fury Beast DDR5 32GB 5600",
    category: "Memory",
    priceBase: 119,
    markup: 18,
    releaseYear: 2022,
    warrantyMonths: 999,
    stock: 45,
    specifications: {
      ram: { sizeGb: 16, modulesCount: 2, speedMhz: 5600, casLatency: 40, voltage: 1.25, rgb: false },
    },
    compatibility: { memoryType: "DDR5", formFactor: "DIMM" },
  }),
  make({
    title: "Corsair Vengeance DDR5 64GB (2x32GB) 6400MHz CL32",
    shortDescription: "64GB DDR5-6400 per workstation e multitasking estremo.",
    description:
      "Kit da 64 GB ideale per content creation, virtualizzazione e gaming moderno. Profili XMP 3.0 e stencil PCB ottimizzato per l'integritÃ  del segnale.",
    highlights: [
      "2x32GB DDR5-6400 CL32",
      "Profilo XMP 3.0 pronto",
      "PMIC on-die per alimentazione stabile",
      "Dissipatore in alluminio anodizzato",
    ],
    componentType: "RAM",
    brand: "Corsair",
    model: "Vengeance DDR5 64GB 6400",
    category: "Memory",
    priceBase: 289,
    markup: 16,
    releaseYear: 2023,
    warrantyMonths: 120,
    stock: 18,
    specifications: {
      ram: { sizeGb: 32, modulesCount: 2, speedMhz: 6400, casLatency: 32, voltage: 1.4, rgb: false },
    },
    compatibility: { memoryType: "DDR5", formFactor: "DIMM" },
  }),
  make({
    title: "Crucial Pro DDR5 32GB (2x16GB) 5600MHz",
    shortDescription: "32GB DDR5-5600 Micron NAND: affidabilitÃ  professionale.",
    description:
      "Micron-Crucial propone uno dei kit piÃ¹ affidabili della categoria, pensato per workstation e build professionali con necessitÃ  di uptime continuo.",
    highlights: [
      "2x16GB DDR5-5600",
      "Die Micron originali",
      "Compatibile Intel XMP 3.0",
      "Garanzia a vita",
    ],
    componentType: "RAM",
    brand: "Crucial",
    model: "Pro DDR5 32GB 5600",
    category: "Memory",
    priceBase: 109,
    markup: 19,
    releaseYear: 2023,
    warrantyMonths: 999,
    stock: 35,
    specifications: {
      ram: { sizeGb: 16, modulesCount: 2, speedMhz: 5600, casLatency: 46, voltage: 1.1, rgb: false },
    },
    compatibility: { memoryType: "DDR5", formFactor: "DIMM" },
  }),

  // ============================================================
  // SSD (5) ----------------------------------------------------
  // ============================================================
  make({
    title: "Samsung 990 Pro NVMe SSD 2TB",
    shortDescription: "PCIe 4.0 top di gamma: fino a 7450 MB/s.",
    description:
      "Controller Samsung Pascal e NAND V7 TLC. Ottimizzato per DirectStorage e gaming next-gen, con un endurance di 1200 TBW.",
    highlights: ["Read 7450 MB/s", "Write 6900 MB/s", "Endurance 1200 TBW", "DRAM cache LPDDR4"],
    componentType: "SSD",
    brand: "Samsung",
    model: "990 Pro 2TB",
    category: "Storage",
    priceBase: 189,
    markup: 15,
    releaseYear: 2022,
    warrantyMonths: 60,
    stock: 25,
    specifications: {
      ssd: {
        capacityGb: 2000,
        interface: "NVMe PCIe 4.0",
        readMbS: 7450,
        writeMbS: 6900,
        tbw: 1200,
        controller: "Samsung Pascal",
        nandType: "V7 TLC",
        dramCache: true,
      },
    },
    compatibility: { formFactor: "M.2 2280", interface: "NVMe PCIe 4.0", pciExpressVersion: "4.0" },
  }),
  make({
    title: "WD_BLACK SN850X NVMe SSD 2TB",
    shortDescription: "Gen4 gaming-grade con Game Mode 2.0.",
    description:
      "SSD NVMe di fascia enthusiast con modalitÃ  Game Mode 2.0 che anticipa le richieste di cache. Dissipatore opzionale disponibile.",
    highlights: ["Read 7300 MB/s", "Write 6600 MB/s", "1200 TBW", "Game Mode 2.0"],
    componentType: "SSD",
    brand: "Western Digital",
    model: "WD_BLACK SN850X 2TB",
    category: "Storage",
    priceBase: 179,
    markup: 15,
    releaseYear: 2022,
    warrantyMonths: 60,
    stock: 22,
    specifications: {
      ssd: {
        capacityGb: 2000,
        interface: "NVMe PCIe 4.0",
        readMbS: 7300,
        writeMbS: 6600,
        tbw: 1200,
        controller: "WD G2",
        nandType: "BiCS5 TLC",
        dramCache: true,
      },
    },
    compatibility: { formFactor: "M.2 2280", interface: "NVMe PCIe 4.0", pciExpressVersion: "4.0" },
  }),
  make({
    title: "Crucial T700 NVMe SSD 2TB",
    shortDescription: "PCIe 5.0 estremo: fino a 12400 MB/s in lettura.",
    description:
      "Il primo SSD consumer a superare abbondantemente i 12 GB/s grazie al PCIe 5.0. Dissipatore integrato per sostenere le performance sotto carico.",
    highlights: ["Read 12400 MB/s", "Write 11800 MB/s", "PCIe 5.0 x4", "Dissipatore integrato"],
    componentType: "SSD",
    brand: "Crucial",
    model: "T700 2TB",
    category: "Storage",
    priceBase: 299,
    markup: 14,
    releaseYear: 2023,
    warrantyMonths: 60,
    stock: 12,
    specifications: {
      ssd: {
        capacityGb: 2000,
        interface: "NVMe PCIe 5.0",
        readMbS: 12400,
        writeMbS: 11800,
        tbw: 1200,
        controller: "Phison E26",
        nandType: "Micron 232L TLC",
        dramCache: true,
      },
    },
    compatibility: { formFactor: "M.2 2280", interface: "NVMe PCIe 5.0", pciExpressVersion: "5.0" },
  }),
  make({
    title: "Seagate FireCuda 530 NVMe SSD 2TB",
    shortDescription: "Gen4 con endurance elevata (2550 TBW).",
    description:
      "SSD orientato ai creator e agli utenti che richiedono massima resistenza. Controller Phison E18 e NAND Micron 176-layer.",
    highlights: ["Read 7300 MB/s", "Write 6900 MB/s", "2550 TBW", "Dissipatore opzionale"],
    componentType: "SSD",
    brand: "Seagate",
    model: "FireCuda 530 2TB",
    category: "Storage",
    priceBase: 199,
    markup: 15,
    releaseYear: 2022,
    warrantyMonths: 60,
    stock: 20,
    specifications: {
      ssd: {
        capacityGb: 2000,
        interface: "NVMe PCIe 4.0",
        readMbS: 7300,
        writeMbS: 6900,
        tbw: 2550,
        controller: "Phison E18",
        nandType: "Micron 176L TLC",
        dramCache: true,
      },
    },
    compatibility: { formFactor: "M.2 2280", interface: "NVMe PCIe 4.0", pciExpressVersion: "4.0" },
  }),
  make({
    title: "Samsung 980 Pro NVMe SSD 1TB",
    shortDescription: "Classico SSD Gen4 da 1TB a prezzo aggressivo.",
    description:
      "Versione piÃ¹ piccola dell'iconico 980 Pro: ottimo per sistema operativo + 1-2 titoli AAA, con velocitÃ  da 7000 MB/s.",
    highlights: ["Read 7000 MB/s", "Write 5000 MB/s", "600 TBW", "Ottimo per boot drive"],
    componentType: "SSD",
    brand: "Samsung",
    model: "980 Pro 1TB",
    category: "Storage",
    priceBase: 99,
    markup: 17,
    releaseYear: 2022,
    warrantyMonths: 60,
    stock: 40,
    specifications: {
      ssd: {
        capacityGb: 1000,
        interface: "NVMe PCIe 4.0",
        readMbS: 7000,
        writeMbS: 5000,
        tbw: 600,
        controller: "Samsung Elpis",
        nandType: "V6 TLC",
        dramCache: true,
      },
    },
    compatibility: { formFactor: "M.2 2280", interface: "NVMe PCIe 4.0", pciExpressVersion: "4.0" },
  }),

  // ============================================================
  // HDD (5) ----------------------------------------------------
  // ============================================================
  make({
    title: "Western Digital Red Pro 8TB NAS HDD",
    shortDescription: "8TB 7200 RPM per NAS e file-server 24/7.",
    description:
      "Hard disk progettato per ambienti NAS multi-bay con workload 24/7. Tecnologia CMR per massima affidabilitÃ .",
    highlights: ["8 TB CMR", "7200 RPM, 256 MB cache", "MTBF 1M ore", "Ideale per NAS 1-24 bay"],
    componentType: "HDD",
    brand: "Western Digital",
    model: "Red Pro 8TB",
    category: "Storage",
    priceBase: 219,
    markup: 14,
    releaseYear: 2023,
    warrantyMonths: 60,
    stock: 18,
    specifications: {
      ssd: {
        capacityGb: 8000,
        interface: "SATA 6 Gb/s",
        readMbS: 240,
        writeMbS: 240,
        tbw: 300,
        nandType: "CMR",
        dramCache: true,
      },
    },
    compatibility: { formFactor: "3.5\"", interface: "SATA III" },
  }),
  make({
    title: "Seagate IronWolf 6TB NAS HDD",
    shortDescription: "6TB 5400 RPM CMR per NAS fino a 8 bay.",
    description:
      "Soluzione affidabile per storage di backup domestico e piccolo ufficio. Sensori AgileArray ottimizzati per ambienti multi-bay.",
    highlights: ["6 TB CMR", "5400 RPM, 256 MB cache", "AgileArray per NAS", "MTBF 1M ore"],
    componentType: "HDD",
    brand: "Seagate",
    model: "IronWolf 6TB",
    category: "Storage",
    priceBase: 159,
    markup: 15,
    releaseYear: 2022,
    warrantyMonths: 36,
    stock: 25,
    specifications: {
      ssd: {
        capacityGb: 6000,
        interface: "SATA 6 Gb/s",
        readMbS: 180,
        writeMbS: 180,
        nandType: "CMR",
      },
    },
    compatibility: { formFactor: "3.5\"", interface: "SATA III" },
  }),
  make({
    title: "Western Digital Black 4TB Gaming HDD",
    shortDescription: "4TB 7200 RPM con cache 256 MB per storage games.",
    description:
      "Disco meccanico di fascia alta pensato per libreria Steam e archivi multimediali. Alta affidabilitÃ  e garanzia 5 anni.",
    highlights: ["4 TB CMR", "7200 RPM", "256 MB cache", "Garanzia 5 anni"],
    componentType: "HDD",
    brand: "Western Digital",
    model: "Black 4TB",
    category: "Storage",
    priceBase: 159,
    markup: 15,
    releaseYear: 2022,
    warrantyMonths: 60,
    stock: 22,
    specifications: {
      ssd: {
        capacityGb: 4000,
        interface: "SATA 6 Gb/s",
        readMbS: 227,
        writeMbS: 227,
        nandType: "CMR",
      },
    },
    compatibility: { formFactor: "3.5\"", interface: "SATA III" },
  }),
  make({
    title: "Seagate Exos X18 16TB Enterprise HDD",
    shortDescription: "16TB enterprise per data-center e NAS professionali.",
    description:
      "Classe enterprise con workload rating 550 TB/anno. Tecnologia a elio sigillato per ridurre attrito e consumi.",
    highlights: ["16 TB CMR", "7200 RPM, 256 MB cache", "Helium sealed", "MTBF 2.5M ore"],
    componentType: "HDD",
    brand: "Seagate",
    model: "Exos X18 16TB",
    category: "Storage",
    priceBase: 329,
    markup: 12,
    releaseYear: 2022,
    warrantyMonths: 60,
    stock: 10,
    specifications: {
      ssd: {
        capacityGb: 16000,
        interface: "SATA 6 Gb/s",
        readMbS: 270,
        writeMbS: 270,
        nandType: "CMR",
      },
    },
    compatibility: { formFactor: "3.5\"", interface: "SATA III" },
  }),
  make({
    title: "Toshiba N300 10TB NAS HDD",
    shortDescription: "10TB CMR 7200 RPM per NAS 24/7.",
    description:
      "Hard disk NAS Toshiba con tecnologia anti-vibrazione. Ideale per NAS fino a 8 bay e server SOHO.",
    highlights: ["10 TB CMR", "7200 RPM", "256 MB cache", "Garanzia 3 anni"],
    componentType: "HDD",
    brand: "Toshiba",
    model: "N300 10TB",
    category: "Storage",
    priceBase: 249,
    markup: 14,
    releaseYear: 2023,
    warrantyMonths: 36,
    stock: 15,
    specifications: {
      ssd: {
        capacityGb: 10000,
        interface: "SATA 6 Gb/s",
        readMbS: 260,
        writeMbS: 260,
        nandType: "CMR",
      },
    },
    compatibility: { formFactor: "3.5\"", interface: "SATA III" },
  }),

  // ============================================================
  // Motherboard (5) --------------------------------------------
  // ============================================================
  make({
    title: "ASUS ROG STRIX Z790-E Gaming WIFI II",
    shortDescription: "Z790 enthusiast ATX: DDR5-8000, Wi-Fi 7, 5x M.2.",
    description:
      "Motherboard di punta per LGA1700 con VRM a 18+1+2 fasi da 90A, memoria DDR5 fino a 8000+ MT/s e connettivitÃ  next-gen.",
    highlights: [
      "Socket LGA1700, CPU Intel 12-14 gen",
      "VRM 18+1+2 fasi da 90A",
      "DDR5 fino a 8000 MT/s, 4 slot, 192 GB",
      "PCIe 5.0, 5 M.2 (1x PCIe 5.0), Wi-Fi 7",
    ],
    componentType: "Motherboard",
    brand: "ASUS",
    model: "ROG STRIX Z790-E II",
    category: "Motherboards",
    priceBase: 499,
    markup: 13,
    releaseYear: 2023,
    warrantyMonths: 36,
    stock: 15,
    specifications: {
      motherboard: {
        chipset: "Intel Z790",
        memorySlots: 4,
        maxMemoryGb: 192,
        pcieVersion: "5.0",
        m2Slots: 5,
        sataPorts: 4,
        wifi: true,
        bluetooth: true,
      },
    },
    compatibility: {
      socket: "LGA1700",
      chipset: "Intel Z790",
      memoryType: "DDR5",
      formFactor: "ATX",
      memorySlots: 4,
      maxMemoryGb: 192,
      pciExpressVersion: "5.0",
    },
  }),
  make({
    title: "MSI MPG B650 Edge WIFI",
    shortDescription: "AM5 ATX con PCIe 5.0 e DDR5: base ideale per Ryzen 7000.",
    description:
      "Motherboard AM5 mid-range con Wi-Fi 6E, 4 slot DDR5 e design minimale con RGB Mystic Light sui dissipatori VRM.",
    highlights: [
      "Socket AM5 per Ryzen 7000/8000/9000",
      "VRM 14+2+1 fasi",
      "PCIe 5.0, DDR5 fino a 6600+ MHz",
      "Wi-Fi 6E, BT 5.3, 2.5 GbE LAN",
    ],
    componentType: "Motherboard",
    brand: "MSI",
    model: "MPG B650 Edge WIFI",
    category: "Motherboards",
    priceBase: 279,
    markup: 13,
    releaseYear: 2022,
    warrantyMonths: 36,
    stock: 20,
    specifications: {
      motherboard: {
        chipset: "AMD B650",
        memorySlots: 4,
        maxMemoryGb: 128,
        pcieVersion: "5.0",
        m2Slots: 3,
        sataPorts: 6,
        wifi: true,
        bluetooth: true,
      },
    },
    compatibility: {
      socket: "AM5",
      chipset: "AMD B650",
      memoryType: "DDR5",
      formFactor: "ATX",
      memorySlots: 4,
      maxMemoryGb: 128,
      pciExpressVersion: "5.0",
    },
  }),
  make({
    title: "ASUS TUF Gaming B650-PLUS WIFI",
    shortDescription: "AM5 ATX accessibile con TUF durability e Wi-Fi 6.",
    description:
      "Soluzione mid-range ASUS per Ryzen 7000. Componentistica militare-grade e 4 slot DDR5 a 6400+ MHz.",
    highlights: [
      "Socket AM5, chipset B650",
      "VRM 12+2 fasi DrMOS",
      "DDR5 6400+ MHz, 4 slot",
      "2.5 GbE LAN + Wi-Fi 6",
    ],
    componentType: "Motherboard",
    brand: "ASUS",
    model: "TUF Gaming B650-PLUS",
    category: "Motherboards",
    priceBase: 229,
    markup: 14,
    releaseYear: 2022,
    warrantyMonths: 36,
    stock: 25,
    specifications: {
      motherboard: {
        chipset: "AMD B650",
        memorySlots: 4,
        maxMemoryGb: 128,
        pcieVersion: "4.0",
        m2Slots: 2,
        sataPorts: 4,
        wifi: true,
        bluetooth: true,
      },
    },
    compatibility: {
      socket: "AM5",
      chipset: "AMD B650",
      memoryType: "DDR5",
      formFactor: "ATX",
      memorySlots: 4,
      maxMemoryGb: 128,
      pciExpressVersion: "4.0",
    },
  }),
  make({
    title: "Gigabyte X670E Aorus Elite AX",
    shortDescription: "X670E ATX con PCIe 5.0 everywhere per build enthusiast.",
    description:
      "Motherboard premium Gigabyte con doppio chipset X670E, Wi-Fi 6E e VRM 16+2+2 fasi. Pensata per CPU Ryzen top di gamma.",
    highlights: [
      "Socket AM5, chipset X670E",
      "PCIe 5.0 su slot GPU e M.2",
      "VRM 16+2+2 fasi",
      "Wi-Fi 6E, BT 5.2",
    ],
    componentType: "Motherboard",
    brand: "Gigabyte",
    model: "X670E Aorus Elite AX",
    category: "Motherboards",
    priceBase: 349,
    markup: 13,
    releaseYear: 2022,
    warrantyMonths: 36,
    stock: 14,
    specifications: {
      motherboard: {
        chipset: "AMD X670E",
        memorySlots: 4,
        maxMemoryGb: 128,
        pcieVersion: "5.0",
        m2Slots: 4,
        sataPorts: 4,
        wifi: true,
        bluetooth: true,
      },
    },
    compatibility: {
      socket: "AM5",
      chipset: "AMD X670E",
      memoryType: "DDR5",
      formFactor: "ATX",
      memorySlots: 4,
      maxMemoryGb: 128,
      pciExpressVersion: "5.0",
    },
  }),
  make({
    title: "ASRock B760M Pro RS DDR4",
    shortDescription: "mATX B760 economica per chi riusa RAM DDR4.",
    description:
      "Motherboard compatta micro-ATX per CPU Intel 12/13/14 gen, con supporto DDR4 per riutilizzare kit esistenti.",
    highlights: [
      "Socket LGA1700, chipset B760",
      "4 slot DDR4 fino a 5333 MHz",
      "PCIe 4.0 + 2 M.2",
      "2.5 GbE LAN",
    ],
    componentType: "Motherboard",
    brand: "ASRock",
    model: "B760M Pro RS DDR4",
    category: "Motherboards",
    priceBase: 129,
    markup: 16,
    releaseYear: 2023,
    warrantyMonths: 36,
    stock: 30,
    specifications: {
      motherboard: {
        chipset: "Intel B760",
        memorySlots: 4,
        maxMemoryGb: 128,
        pcieVersion: "4.0",
        m2Slots: 2,
        sataPorts: 4,
        wifi: false,
        bluetooth: false,
      },
    },
    compatibility: {
      socket: "LGA1700",
      chipset: "Intel B760",
      memoryType: "DDR4",
      formFactor: "mATX",
      memorySlots: 4,
      maxMemoryGb: 128,
      pciExpressVersion: "4.0",
    },
  }),

  // ============================================================
  // PSU (5) ----------------------------------------------------
  // ============================================================
  make({
    title: "Corsair RM1000e 1000W 80+ Gold ATX 3.0",
    shortDescription: "1000W ATX 3.0 fully modular con 12VHPWR.",
    description:
      "Alimentatore ATX 3.0 pienamente modulare con connettore 12VHPWR 600W nativo per GPU RTX 40 e ventola Zero-RPM.",
    highlights: ["80+ Gold (>90% efficienza)", "ATX 3.0 + 12VHPWR", "Fully modular", "Zero-RPM sotto 40% carico"],
    componentType: "PSU",
    brand: "Corsair",
    model: "RM1000e",
    category: "Power Supplies",
    priceBase: 199,
    markup: 16,
    releaseYear: 2022,
    warrantyMonths: 84,
    stock: 22,
    specifications: {
      psu: {
        wattage: 1000,
        efficiencyRating: "80+ Gold",
        modular: "Full",
        fanSizeMm: 140,
        atxVersion: "ATX 3.0",
        pcie5Connector: true,
      },
    },
    compatibility: { wattage: "1000W", formFactor: "ATX", efficiencyRating: "80+ Gold" },
  }),
  make({
    title: "Corsair HX1200i 1200W 80+ Platinum ATX 3.0",
    shortDescription: "1200W Platinum digitale con iCUE e monitoring.",
    description:
      "Alimentatore digital-ready con controllo via iCUE, certificazione 80+ Platinum e cavi individuali per una gestione estetica premium.",
    highlights: ["80+ Platinum", "ATX 3.0 con 12VHPWR", "Monitoring iCUE", "Ventola MLB 140mm"],
    componentType: "PSU",
    brand: "Corsair",
    model: "HX1200i",
    category: "Power Supplies",
    priceBase: 329,
    markup: 14,
    releaseYear: 2023,
    warrantyMonths: 120,
    stock: 10,
    specifications: {
      psu: {
        wattage: 1200,
        efficiencyRating: "80+ Platinum",
        modular: "Full",
        fanSizeMm: 140,
        atxVersion: "ATX 3.0",
        pcie5Connector: true,
      },
    },
    compatibility: { wattage: "1200W", formFactor: "ATX", efficiencyRating: "80+ Platinum" },
  }),
  make({
    title: "EVGA SuperNOVA 850 G6 80+ Gold",
    shortDescription: "850W Gold fully modular in chassis compatto 140mm.",
    description:
      "Alimentatore compatto pensato per build densi. Fully modular con cavi piatti e garanzia 10 anni.",
    highlights: ["80+ Gold", "Chassis 140mm", "Fully modular flat cables", "Garanzia 10 anni"],
    componentType: "PSU",
    brand: "EVGA",
    model: "SuperNOVA 850 G6",
    category: "Power Supplies",
    priceBase: 139,
    markup: 18,
    releaseYear: 2021,
    warrantyMonths: 120,
    stock: 25,
    specifications: {
      psu: {
        wattage: 850,
        efficiencyRating: "80+ Gold",
        modular: "Full",
        fanSizeMm: 135,
        atxVersion: "ATX 2.4",
        pcie5Connector: false,
      },
    },
    compatibility: { wattage: "850W", formFactor: "ATX", efficiencyRating: "80+ Gold" },
  }),
  make({
    title: "Seasonic Focus GX-850 ATX 3.0",
    shortDescription: "850W Gold Seasonic di riferimento con ATX 3.0.",
    description:
      "Seasonic Focus GX aggiornato al 3.0 con connettore 12VHPWR. Ripple bassissimo e modalitÃ  ibrida silenziosa.",
    highlights: ["80+ Gold", "ATX 3.0 + 12VHPWR", "Fully modular", "10 anni di garanzia"],
    componentType: "PSU",
    brand: "Seasonic",
    model: "Focus GX-850 ATX 3.0",
    category: "Power Supplies",
    priceBase: 159,
    markup: 16,
    releaseYear: 2023,
    warrantyMonths: 120,
    stock: 18,
    specifications: {
      psu: {
        wattage: 850,
        efficiencyRating: "80+ Gold",
        modular: "Full",
        fanSizeMm: 120,
        atxVersion: "ATX 3.0",
        pcie5Connector: true,
      },
    },
    compatibility: { wattage: "850W", formFactor: "ATX", efficiencyRating: "80+ Gold" },
  }),
  make({
    title: "be quiet! Pure Power 12 M 850W 80+ Gold",
    shortDescription: "850W Gold silenzioso con ventola 120mm low-noise.",
    description:
      "Alimentatore semi-modulare con focus sulla silenziositÃ : ventola 120mm a cuscinetto magnetico e pannelli fonoassorbenti interni.",
    highlights: ["80+ Gold", "Ventola 120mm silenziosa", "ATX 3.0", "Garanzia 10 anni"],
    componentType: "PSU",
    brand: "be quiet!",
    model: "Pure Power 12 M 850W",
    category: "Power Supplies",
    priceBase: 129,
    markup: 17,
    releaseYear: 2023,
    warrantyMonths: 120,
    stock: 20,
    specifications: {
      psu: {
        wattage: 850,
        efficiencyRating: "80+ Gold",
        modular: "Full",
        fanSizeMm: 120,
        atxVersion: "ATX 3.0",
        pcie5Connector: true,
      },
    },
    compatibility: { wattage: "850W", formFactor: "ATX", efficiencyRating: "80+ Gold" },
  }),

  // ============================================================
  // Case (5) ---------------------------------------------------
  // ============================================================
  make({
    title: "Lian Li LANCOOL 216 RGB",
    shortDescription: "Mid-tower ATX con airflow mesh e due ventole RGB 160mm.",
    description:
      "Case ATX modulare con frontale mesh e ventole anteriori da 160mm incluse. Supporto AIO fino a 360mm.",
    highlights: ["Supporta E-ATX/ATX/mATX/ITX", "GPU fino a 392mm", "AIO fino a 360mm", "2x ventole 160mm ARGB incluse"],
    componentType: "Case",
    brand: "Lian Li",
    model: "LANCOOL 216 RGB",
    category: "Cases",
    priceBase: 129,
    markup: 17,
    releaseYear: 2023,
    warrantyMonths: 24,
    color: "Nero",
    dimensionsMm: { length: 479, width: 239, height: 494 },
    weightGrams: 10500,
    stock: 18,
    specifications: {
      case: {
        formFactorSupport: ["E-ATX", "ATX", "mATX", "ITX"],
        maxGpuLengthMm: 392,
        maxCoolerHeightMm: 180,
        fanSlotsIncluded: 3,
        radiatorSupport: ["240", "280", "360"],
        sidePanel: "Tempered Glass",
      },
    },
    compatibility: { formFactor: "ATX", maxGpuLengthMm: 392 },
  }),
  make({
    title: "Corsair 5000T RGB",
    shortDescription: "Full tower premium con 208 LED RGB iCUE.",
    description:
      "Case ampio con 208 LED RGB integrati, supporto per AIO fino a 420mm e gestione cavi eccellente.",
    highlights: ["E-ATX/ATX/mATX", "208 LED RGB iCUE", "AIO fino a 420mm", "9 slot ventole"],
    componentType: "Case",
    brand: "Corsair",
    model: "5000T RGB",
    category: "Cases",
    priceBase: 299,
    markup: 15,
    releaseYear: 2021,
    warrantyMonths: 24,
    color: "Nero RGB",
    dimensionsMm: { length: 560, width: 260, height: 530 },
    weightGrams: 18000,
    stock: 10,
    specifications: {
      case: {
        formFactorSupport: ["E-ATX", "ATX", "mATX"],
        maxGpuLengthMm: 420,
        maxCoolerHeightMm: 170,
        fanSlotsIncluded: 3,
        radiatorSupport: ["240", "280", "360", "420"],
        sidePanel: "Tempered Glass",
      },
    },
    compatibility: { formFactor: "ATX", maxGpuLengthMm: 420 },
  }),
  make({
    title: "Fractal Design Meshify 2",
    shortDescription: "Mid-tower high-airflow modulare con tre ventole incluse.",
    description:
      "Fractal Meshify 2 Ã¨ il riferimento per build silent+airflow. Interno totalmente modulare con supporto fino a 9 drive.",
    highlights: ["E-ATX/ATX/mATX/ITX", "GPU fino a 467mm", "3x ventole Dynamic X2 incluse", "Fino a 9 drive bay"],
    componentType: "Case",
    brand: "Fractal Design",
    model: "Meshify 2",
    category: "Cases",
    priceBase: 159,
    markup: 16,
    releaseYear: 2021,
    warrantyMonths: 24,
    color: "Nero",
    dimensionsMm: { length: 542, width: 240, height: 474 },
    weightGrams: 11500,
    stock: 16,
    specifications: {
      case: {
        formFactorSupport: ["E-ATX", "ATX", "mATX", "ITX"],
        maxGpuLengthMm: 467,
        maxCoolerHeightMm: 185,
        fanSlotsIncluded: 3,
        radiatorSupport: ["240", "280", "360", "420"],
        sidePanel: "Tempered Glass",
      },
    },
    compatibility: { formFactor: "ATX", maxGpuLengthMm: 467 },
  }),
  make({
    title: "NZXT H7 Flow 2024",
    shortDescription: "ATX high-airflow minimale con pannello mesh frontale.",
    description:
      "Nuova versione 2024 del popolare H7: rinnovato frontale mesh, migliore gestione cavi e due ventole incluse.",
    highlights: ["ATX/mATX/ITX", "GPU fino a 400mm", "AIO 360mm (top/front)", "2 ventole F120Q incluse"],
    componentType: "Case",
    brand: "NZXT",
    model: "H7 Flow 2024",
    category: "Cases",
    priceBase: 139,
    markup: 17,
    releaseYear: 2024,
    warrantyMonths: 24,
    color: "Bianco",
    dimensionsMm: { length: 480, width: 230, height: 505 },
    weightGrams: 9800,
    stock: 20,
    specifications: {
      case: {
        formFactorSupport: ["ATX", "mATX", "ITX"],
        maxGpuLengthMm: 400,
        maxCoolerHeightMm: 185,
        fanSlotsIncluded: 2,
        radiatorSupport: ["240", "280", "360"],
        sidePanel: "Tempered Glass",
      },
    },
    compatibility: { formFactor: "ATX", maxGpuLengthMm: 400 },
  }),
  make({
    title: "be quiet! Pure Base 500DX",
    shortDescription: "Mid-tower silent con mesh frontale e 3 ventole ARGB.",
    description:
      "Case compatto con equilibrio perfetto tra silenziositÃ  e airflow. Tre ventole Pure Wings 2 ARGB incluse.",
    highlights: ["ATX/mATX/ITX", "GPU fino a 369mm", "AIO 360mm front", "3 ventole 140mm incluse"],
    componentType: "Case",
    brand: "be quiet!",
    model: "Pure Base 500DX",
    category: "Cases",
    priceBase: 109,
    markup: 18,
    releaseYear: 2022,
    warrantyMonths: 36,
    color: "Nero",
    dimensionsMm: { length: 450, width: 232, height: 463 },
    weightGrams: 7900,
    stock: 24,
    specifications: {
      case: {
        formFactorSupport: ["ATX", "mATX", "ITX"],
        maxGpuLengthMm: 369,
        maxCoolerHeightMm: 190,
        fanSlotsIncluded: 3,
        radiatorSupport: ["240", "280", "360"],
        sidePanel: "Tempered Glass",
      },
    },
    compatibility: { formFactor: "ATX", maxGpuLengthMm: 369 },
  }),

  // ============================================================
  // Cooling (5) ------------------------------------------------
  // ============================================================
  make({
    title: "Noctua NH-D15 Chromax Black",
    shortDescription: "Il re dei dissipatori ad aria: 220W TDP in silenzio.",
    description:
      "Dual tower con 6 heatpipe e due ventole NF-A15. SilenziositÃ  di riferimento e garanzia 6 anni.",
    highlights: ["Dual tower 6 heatpipe", "24.6 dB(A) max", "AM5/AM4/LGA1700/1200", "6 anni di garanzia"],
    componentType: "Cooling",
    brand: "Noctua",
    model: "NH-D15 Chromax Black",
    category: "Cooling",
    priceBase: 109,
    markup: 18,
    releaseYear: 2022,
    warrantyMonths: 72,
    stock: 20,
    specifications: {
      cooling: {
        type: "Air",
        fanCount: 2,
        maxFanRpm: 1500,
        noiseDbA: 24.6,
        supportedSockets: ["AM5", "AM4", "LGA1700", "LGA1200", "LGA1151"],
      },
    },
    compatibility: { socket: "LGA1700" },
  }),
  make({
    title: "Corsair iCUE H150i ELITE CAPELLIX XT",
    shortDescription: "AIO 360mm con 33 LED CAPELLIX e gestione iCUE.",
    description:
      "All-in-one premium con 3 ventole ML120 RGB, waterblock iluminato da 33 LED e schermo OLED opzionale.",
    highlights: ["Radiatore 360mm", "3 ventole ML120 RGB", "33 LED CAPELLIX", "AM5/AM4/LGA1700/1200"],
    componentType: "Cooling",
    brand: "Corsair",
    model: "H150i ELITE CAPELLIX XT",
    category: "Cooling",
    priceBase: 199,
    markup: 15,
    releaseYear: 2023,
    warrantyMonths: 60,
    stock: 14,
    specifications: {
      cooling: {
        type: "AIO",
        radiatorSizeMm: 360,
        fanCount: 3,
        maxFanRpm: 2400,
        noiseDbA: 37,
        supportedSockets: ["AM5", "AM4", "LGA1700", "LGA1200"],
      },
    },
    compatibility: { socket: "LGA1700", tdp: "250W" },
  }),
  make({
    title: "Arctic Liquid Freezer III 360 A-RGB",
    shortDescription: "AIO 360mm con VRM fan integrata e rapporto prezzo imbattibile.",
    description:
      "La nuova serie Liquid Freezer III mantiene il DNA Arctic: eccellenti prestazioni termiche, rumorositÃ  ridotta e prezzo honest.",
    highlights: ["Radiatore 360mm", "VRM fan integrata", "Pump Generation IV", "Garanzia 6 anni"],
    componentType: "Cooling",
    brand: "Arctic",
    model: "Liquid Freezer III 360 A-RGB",
    category: "Cooling",
    priceBase: 129,
    markup: 18,
    releaseYear: 2024,
    warrantyMonths: 72,
    stock: 25,
    specifications: {
      cooling: {
        type: "AIO",
        radiatorSizeMm: 360,
        fanCount: 3,
        maxFanRpm: 1900,
        noiseDbA: 33,
        supportedSockets: ["AM5", "AM4", "LGA1851", "LGA1700", "LGA1200"],
      },
    },
    compatibility: { socket: "LGA1700", tdp: "250W" },
  }),
  make({
    title: "be quiet! Dark Rock Pro 4",
    shortDescription: "Dissipatore dual tower silenzioso con 7 heatpipe.",
    description:
      "Dissipatore premium be quiet! con rivestimento nero opaco, dual tower e due ventole Silent Wings. 250W TDP gestiti in silenzio assoluto.",
    highlights: ["Dual tower 7 heatpipe", "24.3 dB(A) max", "250W TDP", "Compatibile AM5/AM4/LGA1700"],
    componentType: "Cooling",
    brand: "be quiet!",
    model: "Dark Rock Pro 4",
    category: "Cooling",
    priceBase: 99,
    markup: 19,
    releaseYear: 2022,
    warrantyMonths: 36,
    stock: 22,
    specifications: {
      cooling: {
        type: "Air",
        fanCount: 2,
        maxFanRpm: 1500,
        noiseDbA: 24.3,
        supportedSockets: ["AM5", "AM4", "LGA1700", "LGA1200"],
      },
    },
    compatibility: { socket: "LGA1700" },
  }),
  make({
    title: "NZXT Kraken Elite 360 RGB",
    shortDescription: "AIO 360mm con display LCD 2.36\" personalizzabile.",
    description:
      "AIO top di gamma NZXT con schermo LCD sul waterblock per gif/statistiche e ventole F120 RGB Core.",
    highlights: ["Radiatore 360mm", "LCD 2.36\" 640x640", "3 ventole F120 RGB Core", "Software CAM"],
    componentType: "Cooling",
    brand: "NZXT",
    model: "Kraken Elite 360 RGB",
    category: "Cooling",
    priceBase: 319,
    markup: 13,
    releaseYear: 2023,
    warrantyMonths: 72,
    stock: 10,
    specifications: {
      cooling: {
        type: "AIO",
        radiatorSizeMm: 360,
        fanCount: 3,
        maxFanRpm: 1800,
        noiseDbA: 36,
        supportedSockets: ["AM5", "AM4", "LGA1700", "LGA1200"],
      },
    },
    compatibility: { socket: "LGA1700", tdp: "280W" },
  }),

  // ============================================================
  // Monitor (5) ------------------------------------------------
  // ============================================================
  make({
    title: "LG 27GN950-B UltraGear 27\" 4K 144Hz",
    shortDescription: "27\" Nano IPS 4K 144Hz con 1ms GTG e G-Sync Compatible.",
    description:
      "Monitor 4K IPS ad alto refresh per gaming di fascia entusiasta. Copertura 98% DCI-P3 e HDR600.",
    highlights: ["4K 144Hz Nano IPS", "1ms GTG, HDR600", "G-Sync + FreeSync Premium", "HDMI 2.1 + DP 1.4"],
    componentType: "Monitor",
    brand: "LG",
    model: "27GN950-B",
    category: "Monitors",
    priceBase: 799,
    markup: 12,
    releaseYear: 2020,
    warrantyMonths: 24,
    stock: 10,
    specifications: {
      details: {
        Resolution: "3840 x 2160 (4K)",
        "Refresh Rate": "144 Hz",
        "Response Time": "1ms GTG",
        Panel: "Nano IPS",
      },
    },
    compatibility: { interface: "DisplayPort 1.4, HDMI 2.1" },
  }),
  make({
    title: "ASUS ROG Swift PG27AQDM 27\" QHD 240Hz OLED",
    shortDescription: "27\" QHD OLED 240Hz: punto di riferimento esport.",
    description:
      "Nuovo pannello OLED WOLED di LG Display con 240Hz, 0.03ms GTG e HDR vero. Il monitor piÃ¹ completo per competitive gaming.",
    highlights: ["QHD OLED 240Hz", "0.03ms GTG", "HDR10 true-black", "DisplayPort 1.4 + HDMI 2.1"],
    componentType: "Monitor",
    brand: "ASUS",
    model: "ROG Swift PG27AQDM",
    category: "Monitors",
    priceBase: 999,
    markup: 11,
    releaseYear: 2023,
    warrantyMonths: 36,
    stock: 8,
    specifications: {
      details: {
        Resolution: "2560 x 1440 (QHD)",
        "Refresh Rate": "240 Hz",
        "Response Time": "0.03ms GTG",
        Panel: "WOLED",
      },
    },
    compatibility: { interface: "DisplayPort 1.4, HDMI 2.1" },
  }),
  make({
    title: "Samsung Odyssey G7 32\" QHD 240Hz Curvo",
    shortDescription: "32\" QHD VA curvo 1000R a 240Hz per gaming immersivo.",
    description:
      "Monitor curvo Samsung Odyssey G7 con pannello VA 1000R, 240Hz, HDR600 e 1ms MPRT. Taglio 32 pollici immersivo.",
    highlights: ["QHD 240Hz VA curvo 1000R", "1ms MPRT, HDR600", "G-Sync + FreeSync Premium Pro", "USB hub integrato"],
    componentType: "Monitor",
    brand: "Samsung",
    model: "Odyssey G7 32\"",
    category: "Monitors",
    priceBase: 699,
    markup: 13,
    releaseYear: 2022,
    warrantyMonths: 24,
    stock: 12,
    specifications: {
      details: {
        Resolution: "2560 x 1440 (QHD)",
        "Refresh Rate": "240 Hz",
        "Response Time": "1ms MPRT",
        Panel: "VA Curved 1000R",
      },
    },
    compatibility: { interface: "DisplayPort 1.4, HDMI 2.0" },
  }),
  make({
    title: "Dell Alienware AW3423DWF 34\" UltraWide QD-OLED 165Hz",
    shortDescription: "34\" UltraWide QD-OLED 165Hz curvo: cinema + gaming.",
    description:
      "Il monitor preferito dai recensori: pannello QD-OLED Samsung, 165Hz, 0.1ms e HDR True Black 400. Curvatura 1800R.",
    highlights: ["UltraWide QD-OLED 3440x1440", "165 Hz, 0.1ms GTG", "HDR True Black 400", "3 anni di garanzia OLED"],
    componentType: "Monitor",
    brand: "Dell",
    model: "Alienware AW3423DWF",
    category: "Monitors",
    priceBase: 899,
    markup: 12,
    releaseYear: 2023,
    warrantyMonths: 36,
    stock: 9,
    specifications: {
      details: {
        Resolution: "3440 x 1440 (UW-QHD)",
        "Refresh Rate": "165 Hz",
        "Response Time": "0.1ms GTG",
        Panel: "QD-OLED Curved 1800R",
      },
    },
    compatibility: { interface: "DisplayPort 1.4, HDMI 2.0" },
  }),
  make({
    title: "Gigabyte M27Q-X 27\" QHD 240Hz IPS",
    shortDescription: "27\" IPS QHD 240Hz con KVM integrato: il best-value.",
    description:
      "Monitor 240Hz QHD IPS con KVM switch, USB-C e tactical crosshair. Ottimo rapporto qualitÃ /prezzo.",
    highlights: ["QHD 240Hz IPS", "0.5ms GTG", "KVM switch + USB-C", "FreeSync Premium"],
    componentType: "Monitor",
    brand: "Gigabyte",
    model: "M27Q-X",
    category: "Monitors",
    priceBase: 499,
    markup: 14,
    releaseYear: 2022,
    warrantyMonths: 36,
    stock: 15,
    specifications: {
      details: {
        Resolution: "2560 x 1440 (QHD)",
        "Refresh Rate": "240 Hz",
        "Response Time": "0.5ms GTG",
        Panel: "IPS",
      },
    },
    compatibility: { interface: "DisplayPort 1.4, HDMI 2.0" },
  }),
];

async function seedDatabase() {
  try {
    await connectDatabase();
    console.log("Connected to database");

    // Clear existing products
    await Product.deleteMany({});
    console.log("Cleared existing products");

    // Insert new products
    const preparedProducts = products.map((product) => ({
      ...product,
      inStock: (Number(product.stock) || 0) > 0,
    }));
    const insertedProducts = await Product.insertMany(preparedProducts);
    console.log(`Successfully seeded ${insertedProducts.length} products`);

    process.exit(0);
  } catch (error) {
    console.error("Error seeding database:", error);
    process.exit(1);
  }
}

seedDatabase();
